### ISSUE TITLE
BCML errors

### ISSUE THREAD

**Issue by Longball-Larry** [Torphedo/BOTW-ModdingGuide#3]
getting the below errors the moment I open BCML or try to install the mod

I have tried multiple version of python for good measure. same error every time 

have also tried running everything as administrator to rule that out. spent hours scouring the internet and only found a handful of people with similar issues and no solutions. The files its complaining about are all there

I've followed the guide many times over to ensure I'm not missing anything. 

# when opening BCML

Traceback (most recent call last):
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\_api.py", line 32, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\_api.py", line 83, in sanity_check
    util.sanity_check()
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\util.py", line 490, in sanity_check
    get_game_dir()
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\util.py", line 670, in get_game_dir
    raise FileNotFoundError(
FileNotFoundError: The BOTW game dump directory has not been set or does not exist.

-------------------------------------------------------------------------------------------------------------------------
# When running install

Traceback (most recent call last):
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\_api.py", line 32, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\install.py", line 265, in do_and_refresh
    refresh_master_export()
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\install.py", line 274, in refresh_master_export
    link_master_mod()
  File "C:\Users\brett\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\install.py", line 744, in link_master_mod
    rsext.manager.link_master_mod(str(output) if output else None)
RuntimeError: Failed to create output directory junction

Caused by:
    Incorrect function. (os error 1)

**Comment by Torphedo** [comment]
Ask the creator, he's in this Discord server: [https://discord.gg/y7VJqMB329](https://discord.gg/y7VJqMB329)
